[package]
name = "mcmeta"
version = "0.1.0"
edition = "2024"
description = "A Metadata server for Minecraft launchers and others"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6"
eyre = "0.6"
axum = "0.8.1"
clap = { version = "4.5.32", features = ["derive"] }
config = "0.15.11"
dotenv = "0.15.0"
futures = "0.3.31"
git2 = "0.20.0"
hyper = "1.6.0"
lazy_static = "1.5.0"
libmcmeta = { path = "../libmcmeta" }
regex = "1.11.1"
reqwest = { version = "0.12.14", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde_valid = "1.0.5"
serde_path_to_error = "0.1"
serde_with = "3.12.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
tempdir = "0.3.7"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
zip = { version = "2.3.0", default-features = false, features = [
  "aes-crypto",
  "bzip2",
  "deflate64",
  "deflate",
  "lzma",
  "zstd",
  "xz",
  "chrono",
] }
async-trait = "0.1.88"
enum_dispatch = "0.3.13"
sqlx = { version = "0.8", features = [
  "postgres",
  "runtime-tokio",
  "tls-rustls-aws-lc-rs",
  "derive",
  "migrate",
  "chrono",
  "json",
] }
strum = { version = "0.27.1", features = ["derive"] }
itertools = "0.14.0"
chrono = "0.4"
tracing-indicatif = "0.3.9"
indicatif = "0.17.11"
md-5 = "0.10"
