[package]
name = "mcmeta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.18"
config = "0.13.2"
git2 = "0.15.0"
libmcmeta = { path = "../libmcmeta" }
tokio = { version = "1.21.2", features = ["full"] }
